### PR TITLE
Turning in assignment

### PR DESCRIPTION
**Pull request by daltenbern**

### CODE REVIEW

**Comment by daltenbern** [comment]
* [ ] Create a new directory called `02-box-model`
* [ ] Use the `git` cli to initialize a new project
* [ ] Create index.html and app.css files, and generate boilerplates.
* [ ] Checkpoint: Created and committed `index.html` and `app.css` boilerplate
* [ ] Use `hub create` to create a new repository on github called `02-box-model`
* [ ] Use the `git` cli to create a branch called `develop`
* [ ] Checkpoint: Link CSS to HTML page
* [ ] Use `hub pull-request -m "Turning in assignment"` to create a new pull request
* [ ] Post link to pull request on online.theironyard.com
  * [ ] Checkpoint: Create markup (html) to represent one grid item or column with your own github profile
    * [ ] Markup: Wrapper around profile
    * [ ] Markup: Image
    * [ ] Markup: Username
    * [ ] Markup: List of repos
      * [ ] Markup: Repo name
      * [ ] Markup: Repo language dot
      * [ ] Markup: Repo language name
  * [ ] Checkpoint: Duplicate markup of your column and look for more popular github users across different languages
  * [ ] Markup: Nav bar
    * [ ] Markup: Nav bar left
    * [ ] Markup: Nav bar right
  * [ ] Complete: Pushed `index.html`
* [ ] Add styles for page
  * [ ] Checkpoint: Style Nav bar (give it background, and place the text and links where appropriate)
  * [ ] Checkpoint: Create a "three up" grid (make your columns three wide across the page)
  * [ ] Checkpoint: Style profile image
  * [ ] Checkpoint: Style name
  * [ ] Checkpoint: Style username
  * [ ] Checkpoint: Style repo list
  * [ ] Checkpoint: Style repo name
  * [ ] Checkpoint: Style repo language
  * [ ] Checkpoint: Cleanup Styles

**Comment by rtablada** [comment]
screen shot 2017-02-12 at 7 33 22 pm

Try using the zoom tools. Make sure that the grid centers up and that the repo lists do not jump up next to the avatar image.

**Comment by rtablada** [comment]
The navbar and main content should line up on larger screen sizes.

screen shot 2017-04-14 at 11 24 13 am

**Comment by daltenbern** [comment]
@rtablada moar spam

**Pull request merged**
